# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-01 15:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255)),
                ('task_priority', models.CharField(max_length=10)),
                ('task_status', models.CharField(max_length=20)),
                ('target_date', models.DateField(verbose_name=datetime.date)),
            ],
        ),
    ]
