# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-01 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='target_date',
            field=models.DateField(verbose_name='date'),
        ),
    ]
