# coding: utf-8

"""
Copyright 2016 SmartBear Software

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

    Ref: https://github.com/swagger-api/swagger-codegen
"""

from pprint import pformat
from six import iteritems


class FareRestrictions(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self):
        """
        FareRestrictions - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'refundable': 'bool',
            'change_penalties': 'bool'
        }

        self.attribute_map = {
            'refundable': 'refundable',
            'change_penalties': 'change_penalties'
        }

        self._refundable = None
        self._change_penalties = None

    @property
    def refundable(self):
        """
        Gets the refundable of this FareRestrictions.
        Indicates whether this fare is refundable under some circumstances. Note that a refund charge or penalty may apply

        :return: The refundable of this FareRestrictions.
        :rtype: bool
        """
        return self._refundable

    @refundable.setter
    def refundable(self, refundable):
        """
        Sets the refundable of this FareRestrictions.
        Indicates whether this fare is refundable under some circumstances. Note that a refund charge or penalty may apply

        :param refundable: The refundable of this FareRestrictions.
        :type: bool
        """
        self._refundable = refundable

    @property
    def change_penalties(self):
        """
        Gets the change_penalties of this FareRestrictions.
        Indicates whether this fare allows the itinerary to be changed under some circumstances. Note that a change fee or penalty may apply

        :return: The change_penalties of this FareRestrictions.
        :rtype: bool
        """
        return self._change_penalties

    @change_penalties.setter
    def change_penalties(self, change_penalties):
        """
        Sets the change_penalties of this FareRestrictions.
        Indicates whether this fare allows the itinerary to be changed under some circumstances. Note that a change fee or penalty may apply

        :param change_penalties: The change_penalties of this FareRestrictions.
        :type: bool
        """
        self._change_penalties = change_penalties

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other): 
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """ 
        Returns true if both objects are not equal
        """
        return not self == other

