# coding: utf-8

"""
Copyright 2016 SmartBear Software

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

    Ref: https://github.com/swagger-api/swagger-codegen
"""

from pprint import pformat
from six import iteritems


class FlightSearchItinerary(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self):
        """
        FlightSearchItinerary - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'outbound': 'FlightSearchBound',
            'inbound': 'FlightSearchBound'
        }

        self.attribute_map = {
            'outbound': 'outbound',
            'inbound': 'inbound'
        }

        self._outbound = None
        self._inbound = None

    @property
    def outbound(self):
        """
        Gets the outbound of this FlightSearchItinerary.
        The bound container for the flight information for bringing the traveler from the origin airport to the destination airport

        :return: The outbound of this FlightSearchItinerary.
        :rtype: FlightSearchBound
        """
        return self._outbound

    @outbound.setter
    def outbound(self, outbound):
        """
        Sets the outbound of this FlightSearchItinerary.
        The bound container for the flight information for bringing the traveler from the origin airport to the destination airport

        :param outbound: The outbound of this FlightSearchItinerary.
        :type: FlightSearchBound
        """
        self._outbound = outbound

    @property
    def inbound(self):
        """
        Gets the inbound of this FlightSearchItinerary.
        The bound container for the flight information for bringing the traveler from the destination airport to the origin airport

        :return: The inbound of this FlightSearchItinerary.
        :rtype: FlightSearchBound
        """
        return self._inbound

    @inbound.setter
    def inbound(self, inbound):
        """
        Sets the inbound of this FlightSearchItinerary.
        The bound container for the flight information for bringing the traveler from the destination airport to the origin airport

        :param inbound: The inbound of this FlightSearchItinerary.
        :type: FlightSearchBound
        """
        self._inbound = inbound

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other): 
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """ 
        Returns true if both objects are not equal
        """
        return not self == other

