# coding: utf-8

"""
Copyright 2016 SmartBear Software

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

    Ref: https://github.com/swagger-api/swagger-codegen
"""

from pprint import pformat
from six import iteritems


class HotelReservationBookingInfo(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self):
        """
        HotelReservationBookingInfo - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'reservation_code': 'str',
            'status': 'str'
        }

        self.attribute_map = {
            'reservation_code': 'reservation_code',
            'status': 'status'
        }

        self._reservation_code = None
        self._status = None

    @property
    def reservation_code(self):
        """
        Gets the reservation_code of this HotelReservationBookingInfo.
        The identifier of this reservation in the hotel chain's system. This should be provided at the check-in desk to identify your reservation.

        :return: The reservation_code of this HotelReservationBookingInfo.
        :rtype: str
        """
        return self._reservation_code

    @reservation_code.setter
    def reservation_code(self, reservation_code):
        """
        Sets the reservation_code of this HotelReservationBookingInfo.
        The identifier of this reservation in the hotel chain's system. This should be provided at the check-in desk to identify your reservation.

        :param reservation_code: The reservation_code of this HotelReservationBookingInfo.
        :type: str
        """
        self._reservation_code = reservation_code

    @property
    def status(self):
        """
        Gets the status of this HotelReservationBookingInfo.
        An enumeration to represent the reservation status for this hotel reservation. For example&colon; CONFIRMED, CANCELLED, REQUESTED.

        :return: The status of this HotelReservationBookingInfo.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """
        Sets the status of this HotelReservationBookingInfo.
        An enumeration to represent the reservation status for this hotel reservation. For example&colon; CONFIRMED, CANCELLED, REQUESTED.

        :param status: The status of this HotelReservationBookingInfo.
        :type: str
        """
        self._status = status

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other): 
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """ 
        Returns true if both objects are not equal
        """
        return not self == other

